In [ ]:
import numpy as np

In [4]:
N = int(input())
np.arange(N, 0, -1)

7


array([7, 6, 5, 4, 3, 2, 1])

In [3]:
N = int(input())
a = np.diag(np.arange(N, 0, -1), k=0)

print(a)
print('Diagonal (sum): ', np.trace(a))
print('Diagonal (elements): ', np.diagonal(a))

4
[[4 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 1]]
Diagonal (sum):  10
Diagonal (elements):  [4 3 2 1]


In [5]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [19]:
#Первый вариант:

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [46]:
from scipy.spatial import distance
lookalike_users = []

for user in users_stats:
    el = distance.cosine(user, next_user_stats)
    lookalike_users.append(el)
print(lookalike_users)

[0.8, 0.15484574527148343, 0.6000000000000001, 0.20943058495790523, 0.6000000000000001, 1.0, 1.0, 0.05131670194948623, 1.0, 1.0]


In [49]:
#Второй вариант:

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

x = np.array([0, 1, 2, 0, 0, 0])

In [76]:
stats_l = []
stats_d = []

for u in users_stats:
    length = np.linalg.norm( u ) * xLength
    stats_l.append(length)
    dot_ = np.dot( u, x )
    stats_d.append(dot_)
#print(stats_l)
#print(stats_d)

stats_final = np.array(stats_d) / np.array(stats_l)
print(stats_final)

[0.2        0.84515425 0.4        0.79056942 0.4        0.
 0.         0.9486833  0.         0.        ]
